// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Configuration Supabase depuis les variables d'environnement
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://bkdcbrnfzgnafjwnryme.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrZGNicm5memduYWZqd25yeW1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2ODA1MTAsImV4cCI6MjA2MTI1NjUxMH0.cdzP9f_Bg1TlrBs-v1DsOb5Iv-tfK0KURPwZn1hwYMU';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Vérification des variables d'environnement
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('❌ Variables d\'environnement Supabase manquantes!');
  console.log('Assurez-vous d\'avoir configuré:');
  console.log('- VITE_SUPABASE_URL');
  console.log('- VITE_SUPABASE_ANON_KEY');
} else {
  console.log('✅ Configuration Supabase chargée');
  console.log('URL:', SUPABASE_URL);
  console.log('Clé:', SUPABASE_PUBLISHABLE_KEY.substring(0, 20) + '...');
}

// Créer et exporter le client Supabase
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);